# Orbital Debris SQL Queries

This notebook is intentionally SQL-first and contains query work only (no visualizations).

## **Setup And Function Declarations**

In [1]:
import pandas as pd
import sqlite3

def run_query(sql):
    return pd.read_sql(sql, conn)

def query_all_satellites():
    query = """
    SELECT
      norad_id,
      cospar_id,
      object_name,
      launch_year,
      launch_date,
      launch_site,
      owner,
      country_operator,
      object_type
    FROM satellites
    JOIN launch_events ON launch_events.launch_id = satellites.launch_id
    JOIN ownership_operators ON ownership_operators.owner_code = satellites.owner_code;
    """
    return run_query(query)

# Gets a single satellite's information based on NORAD ID
def query_satellite_info(norad_id):
    query = f"""
    SELECT
      norad_id,
      cospar_id,
      object_name,
      launch_year,
      launch_date,
      launch_site,
      owner,
      country_operator,
      object_type
    FROM satellites
    JOIN launch_events ON launch_events.launch_id = satellites.launch_id
    JOIN ownership_operators ON ownership_operators.owner_code = satellites.owner_code
    WHERE norad_id = {norad_id};
    """
    return run_query(query)

def query_satellite_info_list(norad_ids):
    # This will create a comma-separated string of NORAD IDs for the SQL IN clause
    ids = ','.join(str(id) for id in norad_ids)
    
    query = f"""
    SELECT
      norad_id,
      cospar_id,
      object_name,
      launch_year,
      launch_date,
      launch_site,
      owner,
      country_operator,
      object_type
    FROM satellites
    JOIN launch_events ON launch_events.launch_id = satellites.launch_id
    JOIN ownership_operators ON ownership_operators.owner_code = satellites.owner_code
    WHERE norad_id IN ({ids});
    """
    print(f"Querying information for NORAD IDs: {norad_ids}")
    print(f"Executing SQL query:\n{query}")
    return run_query(query)

pd.set_option('display.max_rows', 100)

conn = sqlite3.connect('../data/clean/orbital_debris.db')

In [2]:
df = query_satellite_info(25544)
display(df)

df = query_satellite_info_list([25544, 33591, 43013])
display(df)

df = query_all_satellites()
display(df)

,norad_id,cospar_id,object_name,launch_year,launch_date,launch_site,owner,country_operator,object_type
0,25544,1998-067A,ISS (ZARYA),1998,1998-11-20,Baikonur Cosmodrome,ISS,MULTINATIONAL,PAYLOAD

Querying information for NORAD IDs: [25544, 33591, 43013]
Executing SQL query:

    SELECT
      norad_id,
      cospar_id,
      object_name,
      launch_year,
      launch_date,
      launch_site,
      owner,
      country_operator,
      object_type
    FROM satellites
    JOIN launch_events ON launch_events.launch_id = satellites.launch_id
    JOIN ownership_operators ON ownership_operators.owner_code = satellites.owner_code
    WHERE norad_id IN (25544,33591,43013);

,norad_id,cospar_id,object_name,launch_year,launch_date,launch_site,owner,country_operator,object_type
0,25544,1998-067A,ISS (ZARYA),1998,1998-11-20,Baikonur Cosmodrome,ISS,MULTINATIONAL,PAYLOAD
1,33591,2009-005A,NOAA 19,2009,2009-02-06,Vandenberg AFB,US,USA,PAYLOAD
2,43013,2017-073A,NOAA 20 (JPSS-1),2017,2017-11-18,Vandenberg AFB,US,USA,PAYLOAD

,norad_id,cospar_id,object_name,launch_year,launch_date,launch_site,owner,country_operator,object_type
0,5,1958-002B,VANGUARD 1,1958,1958-03-17,AFETR,US,USA,PAYLOAD
1,11,1959-001A,VANGUARD 2,1959,1959-02-17,AFETR,US,USA,PAYLOAD
2,12,1959-001B,VANGUARD R/B,1959,1959-02-17,AFETR,US,USA,ROCKET BODY
3,16,1958-002A,VANGUARD R/B,1958,1958-03-17,AFETR,US,USA,ROCKET BODY
4,20,1959-007A,VANGUARD 3,1959,1959-09-18,AFETR,US,USA,PAYLOAD
...,...,...,...,...,...,...,...,...,...
33229,68201,2026-052D,OBJECT D,2026,2026-03-16,JSC,PRC,CHINA,PAYLOAD
33230,68202,2026-052E,OBJECT E,2026,2026-03-16,JSC,PRC,CHINA,PAYLOAD
33231,68203,2026-052F,OBJECT F,2026,2026-03-16,JSC,PRC,CHINA,PAYLOAD
33232,68204,2026-052G,OBJECT G,2026,2026-03-16,JSC,PRC,CHINA,PAYLOAD
33233,68205,2026-052H,OBJECT H,2026,2026-03-16,JSC,PRC,CHINA,PAYLOAD

## Primary Question 1: Growth and Decoupling Baseline

In [3]:
# I absolutely detest table aliases in SQL. I find them to be more confusing 
# than helpful, especially when the table names are not that long to begin with.
# I understand that they can be useful in some cases, but I prefer to just write 
# out the full table names for clarity. Nested queries are usually the only time
# I find them to be necessary, and even then I try to avoid them if possible.

q1 = '''
WITH yearly AS (
  SELECT
    launch_events.launch_year AS launch_year,
    COUNT(*) AS objects_launched,
    COUNT(DISTINCT launch_events.launch_id) AS launch_missions,
    SUM(
      CASE
        WHEN UPPER(COALESCE(satellites.object_type, '')) = 'PAYLOAD' THEN 1
        ELSE 0
      END
    ) AS payload_objects
  FROM satellites
  JOIN launch_events ON launch_events.launch_id = satellites.launch_id
  WHERE launch_events.launch_year IS NOT NULL
  GROUP BY launch_events.launch_year
)
SELECT
  launch_year,
  objects_launched,
  launch_missions,
  payload_objects,
  ROUND(100.0 * payload_objects / NULLIF(objects_launched, 0), 2) AS payload_share_pct,
  SUM(objects_launched) OVER (ORDER BY launch_year) AS cumulative_objects
FROM yearly
ORDER BY launch_year;
'''
launch_trend = run_query(q1)
launch_trend.to_csv('../data/clean/queries/pq1_launch_trend.csv', index=False)
launch_trend.head(100)

,launch_year,objects_launched,launch_missions,payload_objects,payload_share_pct,cumulative_objects
0,1958,3,1,1,33.33,3
1,1959,7,5,5,71.43,10
2,1960,13,6,5,38.46,23
3,1961,212,8,9,4.25,235
4,1962,33,15,14,42.42,268
5,1963,91,12,17,18.68,359
6,1964,60,21,28,46.67,419
7,1965,449,33,52,11.58,868
8,1966,207,34,38,18.36,1075
9,1967,95,31,49,51.58,1170
10,1968,217,25,33,15.21,1387
11,1969,137,25,36,26.28,1524
12,1970,370,28,38,10.27,1894
13,1971,148,39,55,37.16,2042
14,1972,125,33,47,37.60,2167
15,1973,278,32,55,19.78,2445
16,1974,264,36,52,19.70,2709
17,1975,370,45,65,17.57,3079
18,1976,436,49,75,17.20,3515
19,1977,339,52,58,17.11,3854
20,1978,337,57,84,24.93,4191
21,1979,185,33,45,24.32,4376
22,1980,141,37,57,40.43,4517
23,1981,645,56,80,12.40,5162
24,1982,261,53,64,24.52,5423
25,1983,166,62,82,49.40,5589
26,1984,240,66,91,37.92,5829
27,1985,220,58,85,38.64,6049
28,1986,174,49,74,42.53,6223
29,1987,376,52,72,19.15,6599
30,1988,293,56,78,26.62,6892
31,1989,339,50,74,21.83,7231
32,1990,293,64,104,35.49,7524
33,1991,497,54,89,17.91,8021
34,1992,373,53,78,20.91,8394
35,1993,831,46,69,8.30,9225
36,1994,242,60,82,33.88,9467
37,1995,242,50,64,26.45,9709
38,1996,117,48,64,54.70,9826
39,1997,268,61,93,34.70,10094
40,1998,157,56,113,71.97,10251
41,1999,2638,59,104,3.94,12889
42,2000,518,61,89,17.18,13407
43,2001,125,38,54,43.20,13532
44,2002,165,41,61,36.97,13697
45,2003,125,47,65,52.00,13822
46,2004,109,41,58,53.21,13931
47,2005,98,36,53,54.08,14029
48,2006,219,46,59,26.94,14248
49,2007,219,46,76,34.70,14467
50,2008,295,50,80,27.12,14762
51,2009,166,54,88,53.01,14928
52,2010,307,55,91,29.64,15235
53,2011,406,59,91,22.41,15641
54,2012,199,56,85,42.71,15840
55,2013,261,57,130,49.81,16101
56,2014,405,68,142,35.06,16506
57,2015,203,66,129,63.55,16709
58,2016,198,62,101,51.01,16907
59,2017,208,70,158,75.96,17115
60,2018,527,93,229,43.45,17642
61,2019,219,72,162,73.97,17861
62,2020,568,83,528,92.96,18429
63,2021,1152,107,1088,94.44,19581
64,2022,2560,150,1856,72.50,22141
65,2023,2436,180,2369,97.25,24577
66,2024,3284,230,2620,79.78,27861
67,2025,4546,303,4444,97.76,32407
68,2026,827,50,798,96.49,33234

## **Primary Question 2: High-Risk Distribution by Altitude Band**

## **Primary Question 3: Zombie Concentration by Owner**

## **Secondary: Object Type × Operational Status**

## **Secondary: User Category Profile**

## **Extra Questions!**

## **Tidy Up!**

In [4]:
# Close the connection.
# Release resources and ensure clean exit (old habits die hard).
conn.close()
print('Connection closed.')

Connection closed.